export { default as Home } from './Home';
export { default as About } from './About';
export { default as SignUp } from './SignUp';
export { default as Board } from './Board';
export { default as Post } from './Post';
// export { default as PhotoBoard } from './PhotoBoard';
export { default as Album } from './Album';
export { default as Photo } from './Photo';
export { default as Docu } from './Document';
export { default as LogIn } from './LogIn';
export { default as MyPage } from './MyPage';
export { default as UserPage } from './UserPage';
export { default as AllComments } from './AllComments';
export { default as AllPosts } from './AllPosts';
