export { default as Home } from './Home';
export { default as About } from './About';
export { default as SignUp } from './SignUp';
export { default as Board } from './Board';
// export { default as PhotoBoard } from './PhotoBoard';
export { default as Album } from './Album';
export { default as Photo } from './Photo';
export { default as Document } from './Document';
export { default as LogIn } from './LogIn';
export { default as UserInfo } from './UserInfo';
